import { Routine } from '../types';

export const PRESET_ROUTINES: Routine[] = [
  {
    id: 'chest-triceps-focus',
    name: 'Chest + Triceps Focus',
    targetMuscles: ['chest', 'triceps'],
    estimatedDurationMin: 55,
    lastPerformed: 'Today (active)',
    isActive: true,
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now(),
    exercises: [
      {
        id: 're-1',
        exerciseId: 'bench-press',
        exerciseName: 'Bench Press',
        muscleGroup: 'chest',
        equipment: 'barbell',
        targetSets: 4,
        targetReps: '8-10',
        targetWeightKg: 85,
        restSeconds: 120,
        order: 1,
      },
      {
        id: 're-2',
        exerciseId: 'incline-dumbbell-press',
        exerciseName: 'Incline Dumbbell Press',
        muscleGroup: 'chest',
        equipment: 'dumbbells',
        targetSets: 3,
        targetReps: '8-12',
        targetWeightKg: 32.5,
        restSeconds: 120,
        order: 2,
      },
      {
        id: 're-3',
        exerciseId: 'cable-fly',
        exerciseName: 'Cable Fly',
        muscleGroup: 'chest',
        equipment: 'cables',
        targetSets: 3,
        targetReps: '12-15',
        targetWeightKg: 15,
        restSeconds: 90,
        order: 3,
      },
      {
        id: 're-4',
        exerciseId: 'rope-pushdown',
        exerciseName: 'Rope Pushdown',
        muscleGroup: 'triceps',
        equipment: 'cables',
        targetSets: 3,
        targetReps: '10-15',
        targetWeightKg: 25,
        restSeconds: 90,
        order: 4,
      },
      {
        id: 're-5',
        exerciseId: 'overhead-extension',
        exerciseName: 'Overhead Extension',
        muscleGroup: 'triceps',
        equipment: 'cables',
        targetSets: 3,
        targetReps: '10-15',
        targetWeightKg: 22.5,
        restSeconds: 90,
        order: 5,
      },
      {
        id: 're-6',
        exerciseId: 'dips',
        exerciseName: 'Dips',
        muscleGroup: 'triceps',
        equipment: 'bodyweight',
        targetSets: 3,
        targetReps: '8-12',
        restSeconds: 90,
        order: 6,
      },
    ],
  },
  {
    id: 'push-day-workout',
    name: 'Push Day Workout',
    targetMuscles: ['chest', 'shoulders', 'triceps'],
    estimatedDurationMin: 50,
    lastPerformed: 'Yesterday',
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now(),
    exercises: [
      {
        id: 're-p1',
        exerciseId: 'bench-press',
        exerciseName: 'Bench Press',
        muscleGroup: 'chest',
        equipment: 'barbell',
        targetSets: 4,
        targetReps: '6-8',
        targetWeightKg: 85,
        restSeconds: 120,
        order: 1,
      },
      {
        id: 're-p2',
        exerciseId: 'overhead-press',
        exerciseName: 'Overhead Barbell Press',
        muscleGroup: 'shoulders',
        equipment: 'barbell',
        targetSets: 3,
        targetReps: '8-10',
        targetWeightKg: 55,
        restSeconds: 120,
        order: 2,
      },
      {
        id: 're-p3',
        exerciseId: 'incline-dumbbell-press',
        exerciseName: 'Incline Dumbbell Press',
        muscleGroup: 'chest',
        equipment: 'dumbbells',
        targetSets: 3,
        targetReps: '8-12',
        targetWeightKg: 30,
        restSeconds: 90,
        order: 3,
      },
      {
        id: 're-p4',
        exerciseId: 'lateral-raise',
        exerciseName: 'Dumbbell Lateral Raise',
        muscleGroup: 'shoulders',
        equipment: 'dumbbells',
        targetSets: 4,
        targetReps: '12-15',
        targetWeightKg: 12,
        restSeconds: 60,
        order: 4,
      },
      {
        id: 're-p5',
        exerciseId: 'skull-crushers',
        exerciseName: 'Skull Crushers',
        muscleGroup: 'triceps',
        equipment: 'barbell',
        targetSets: 3,
        targetReps: '10-12',
        targetWeightKg: 30,
        restSeconds: 90,
        order: 5,
      },
      {
        id: 're-p6',
        exerciseId: 'rope-pushdown',
        exerciseName: 'Rope Pushdown',
        muscleGroup: 'triceps',
        equipment: 'cables',
        targetSets: 3,
        targetReps: '12-15',
        targetWeightKg: 22.5,
        restSeconds: 60,
        order: 6,
      },
    ],
  },
  {
    id: 'pull-day-focus',
    name: 'Pull Day Focus',
    targetMuscles: ['back', 'biceps'],
    estimatedDurationMin: 60,
    lastPerformed: '3 days ago',
    createdAt: Date.now() - 86400000 * 14,
    updatedAt: Date.now(),
    exercises: [
      {
        id: 're-pl1',
        exerciseId: 'deadlift',
        exerciseName: 'Deadlift',
        muscleGroup: 'back',
        equipment: 'barbell',
        targetSets: 4,
        targetReps: '5',
        targetWeightKg: 145,
        restSeconds: 180,
        order: 1,
      },
      {
        id: 're-pl2',
        exerciseId: 'barbell-row',
        exerciseName: 'Barbell Row',
        muscleGroup: 'back',
        equipment: 'barbell',
        targetSets: 3,
        targetReps: '8-10',
        targetWeightKg: 70,
        restSeconds: 120,
        order: 2,
      },
      {
        id: 're-pl3',
        exerciseId: 'lat-pulldown',
        exerciseName: 'Lat Pulldown',
        muscleGroup: 'back',
        equipment: 'cables',
        targetSets: 3,
        targetReps: '10-12',
        targetWeightKg: 65,
        restSeconds: 90,
        order: 3,
      },
      {
        id: 're-pl4',
        exerciseId: 'face-pull',
        exerciseName: 'Face Pull',
        muscleGroup: 'shoulders',
        equipment: 'cables',
        targetSets: 3,
        targetReps: '15-20',
        targetWeightKg: 20,
        restSeconds: 60,
        order: 4,
      },
      {
        id: 're-pl5',
        exerciseId: 'barbell-curl',
        exerciseName: 'Barbell Curl',
        muscleGroup: 'biceps',
        equipment: 'barbell',
        targetSets: 3,
        targetReps: '10-12',
        targetWeightKg: 35,
        restSeconds: 90,
        order: 5,
      },
      {
        id: 're-pl6',
        exerciseId: 'dumbbell-hammer-curl',
        exerciseName: 'Dumbbell Hammer Curl',
        muscleGroup: 'biceps',
        equipment: 'dumbbells',
        targetSets: 3,
        targetReps: '10-12',
        targetWeightKg: 16,
        restSeconds: 60,
        order: 6,
      },
    ],
  },
  {
    id: 'leg-destroyer',
    name: 'Leg Destroyer',
    targetMuscles: ['legs', 'glutes', 'calves'],
    estimatedDurationMin: 65,
    lastPerformed: '5 days ago',
    createdAt: Date.now() - 86400000 * 20,
    updatedAt: Date.now(),
    exercises: [
      {
        id: 're-lg1',
        exerciseId: 'barbell-squat',
        exerciseName: 'Barbell Squat',
        muscleGroup: 'legs',
        equipment: 'barbell',
        targetSets: 4,
        targetReps: '6-8',
        targetWeightKg: 120,
        restSeconds: 150,
        order: 1,
      },
      {
        id: 're-lg2',
        exerciseId: 'leg-press',
        exerciseName: 'Leg Press',
        muscleGroup: 'legs',
        equipment: 'machine',
        targetSets: 3,
        targetReps: '10-12',
        targetWeightKg: 200,
        restSeconds: 120,
        order: 2,
      },
      {
        id: 're-lg3',
        exerciseId: 'romanian-deadlift',
        exerciseName: 'Romanian Deadlift',
        muscleGroup: 'glutes',
        equipment: 'barbell',
        targetSets: 3,
        targetReps: '8-12',
        targetWeightKg: 80,
        restSeconds: 120,
        order: 3,
      },
      {
        id: 're-lg4',
        exerciseId: 'leg-extension',
        exerciseName: 'Leg Extension',
        muscleGroup: 'legs',
        equipment: 'machine',
        targetSets: 3,
        targetReps: '12-15',
        targetWeightKg: 50,
        restSeconds: 60,
        order: 4,
      },
      {
        id: 're-lg5',
        exerciseId: 'hamstring-curl',
        exerciseName: 'Lying Leg Curl',
        muscleGroup: 'legs',
        equipment: 'machine',
        targetSets: 3,
        targetReps: '12-15',
        targetWeightKg: 45,
        restSeconds: 60,
        order: 5,
      },
      {
        id: 're-lg6',
        exerciseId: 'standing-calf-raise',
        exerciseName: 'Standing Calf Raise',
        muscleGroup: 'calves',
        equipment: 'machine',
        targetSets: 4,
        targetReps: '15-20',
        targetWeightKg: 70,
        restSeconds: 60,
        order: 6,
      },
      {
        id: 're-lg7',
        exerciseId: 'hanging-leg-raise',
        exerciseName: 'Hanging Leg Raise',
        muscleGroup: 'abs',
        equipment: 'bodyweight',
        targetSets: 3,
        targetReps: '12-15',
        restSeconds: 60,
        order: 7,
      },
    ],
  },
];
